-- Add expressions for September 9-October 8, 2025 (30 days)
-- This migration adds daily expressions for all Nordic countries

-- Clear any existing expressions for this date range to avoid conflicts
DELETE FROM "Expression" WHERE date >= '2025-09-09' AND date <= '2025-10-08';

-- Swedish expressions (30 days)
INSERT INTO "Expression" (id, date, country, expression, pronunciation, meaning, translation, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), '2025-09-09', 'swedish', 'Inte alla dagar kan vara lika', 'IN-te AL-la DA-gar kan VA-ra LI-ka', 'Not all days are the same', 'Life has its ups and downs, so don''t get discouraged.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-10', 'swedish', 'Att kasta ut barnet med badvattnet', 'ATT KAS-ta ut BAR-net med BAD-vat-tnet', 'To throw out the child with the bathwater', 'Similar to the English expression, meaning to discard something good while getting rid of something bad.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-11', 'swedish', 'Ha is magen', 'HA IS MA-gen', 'To have ice in the stomach', 'To remain calm under pressure or in a stressful situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-12', 'swedish', 'Ligga på latsidan', 'LIG-ga på LAT-si-dan', 'To lie on the lazy side', 'To be lazy or not wanting to do anything.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-13', 'swedish', 'Äta upp sig själv', 'Ä-ta upp sig SJÄLV', 'To eat oneself up', 'To worry or be consumed by anxiety.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-14', 'swedish', 'Slå två flugor i en smäll', 'SLÅ TVÅ FLU-gor i en SMÄLL', 'To hit two flies with one swat', 'Similar to "kill two birds with one stone" in English.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-15', 'swedish', 'Att ha råd med', 'ATT ha RÅD med', 'To have the means for', 'To be able to afford something.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-16', 'swedish', 'Lägga korten på bordet', 'LÄG-ga KOR-ten på BOR-det', 'To lay the cards on the table', 'To be completely honest and transparent.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-17', 'swedish', 'Inte se skogen för alla träd', 'IN-te se SKO-gen för AL-la TRÄD', 'Can''t see the forest for the trees', 'Getting lost in details and missing the bigger picture.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-18', 'swedish', 'Droppa en slant', 'DROP-pa en SLANT', 'Drop a coin', 'To contribute a small amount of money.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-19', 'swedish', 'Vara i samma båt', 'VA-ra i SAM-ma BÅT', 'To be in the same boat', 'To be in the same situation or facing the same challenges.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-20', 'swedish', 'Prata är silver, tiga är guld', 'PRA-ta är SIL-ver, TI-ga är GULD', 'Speaking is silver, silence is golden', 'Sometimes it''s better to stay quiet.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-21', 'swedish', 'Få vatten på sin kvarn', 'FÅ VAT-ten på sin KVARN', 'To get water on one''s mill', 'To receive support or confirmation for one''s arguments.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-22', 'swedish', 'Kasta ut sig med badvattnet', 'KAS-ta ut sig med BAD-vat-tnet', 'Throw yourself out with the bathwater', 'To make a mistake while trying to solve a problem.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-23', 'swedish', 'Inte se längre än näsan räcker', 'IN-te se LÄNG-re än NÄ-san RÄCK-er', 'Not seeing further than one''s nose reaches', 'Being short-sighted or unable to see the bigger picture.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-24', 'swedish', 'Sätta punkt för', 'SÄT-ta PUNKT för', 'To put a period/full stop to', 'To end something definitively.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-25', 'swedish', 'Ha ryggen fri', 'HA RYG-gen FRI', 'To have one''s back free', 'To be without blame or to have nothing to worry about.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-26', 'swedish', 'Dra alla över en kam', 'DRA AL-la Ö-ver en KAM', 'To drag everyone over the same comb', 'To treat everyone the same without differentiation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-27', 'swedish', 'Tappa ansiktet', 'TAP-pa AN-sik-tet', 'To lose one''s face', 'To be embarrassed or lose one''s dignity.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-28', 'swedish', 'Gå på knäna', 'GÅ på KNÄ-na', 'To walk on one''s knees', 'To be completely exhausted.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-29', 'swedish', 'Sätta dit någon', 'SÄT-ta dit NÅ-gon', 'To put someone in their place', 'To expose or catch someone doing something wrong.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-30', 'swedish', 'Bita i det sura äpplet', 'BI-ta i det SU-ra ÄP-plet', 'To bite the sour apple', 'To do something unpleasant that must be done.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-01', 'swedish', 'Ha tummen mitt i handen', 'HA TUM-men MITT i HAN-den', 'To have the thumb in the middle of the hand', 'To be clumsy or unskilled.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-02', 'swedish', 'Sätta ned foten', 'SÄT-ta ned FO-ten', 'To put down one''s foot', 'To put a stop to something or take a firm stand.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-03', 'swedish', 'Sitta i samma sits', 'SIT-ta i SAM-ma SITS', 'To sit in the same situation', 'To be in the same difficult circumstances.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-04', 'swedish', 'Gå på en högerkant', 'GÅ på en HÖ-ger-kant', 'To walk on a right edge', 'To be very careful or precise.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-05', 'swedish', 'Kasta in handduken', 'KAS-ta in HAND-du-ken', 'To throw in the towel', 'To give up, just like in English.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-06', 'swedish', 'Vara som natt och dag', 'VA-ra som NATT och DAG', 'To be like night and day', 'To be completely different.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-07', 'swedish', 'Göra en höna av en fjäder', 'YÖ-ra en HÖ-na av en FYÄ-der', 'To make a hen out of a feather', 'To exaggerate something small.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-08', 'swedish', 'Läsa mellan raderna', 'LÄ-sa MEL-lan RA-der-na', 'To read between the lines', 'To understand the hidden meaning in what someone is saying.', NOW(), NOW());

-- Norwegian expressions (30 days)
INSERT INTO "Expression" (id, date, country, expression, pronunciation, meaning, translation, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), '2025-09-09', 'norwegian', 'Å snu every krone', 'Å SNU ev-er-y KRO-ne', 'To turn every crown', 'To be very careful with money, to be thrifty.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-10', 'norwegian', 'Å ha bein i nesa', 'Å ha BEIN i NE-sa', 'To have bones in the nose', 'To be brave, to have courage and determination.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-11', 'norwegian', 'Å slå to fluer i en smekk', 'Å SLÅ to FLU-er i en SMEKK', 'To hit two flies in one swat', 'Similar to "kill two birds with one stone" in English.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-12', 'norwegian', 'Å gå på en smell', 'Å GÅ på en SMELL', 'To go on a bang', 'To take a risk or face a challenge head-on.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-13', 'norwegian', 'Å ha hodet over vannet', 'Å ha HO-det O-ver VAN-net', 'To have one''s head above water', 'To barely manage financially or survive a difficult situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-14', 'norwegian', 'Å kaste kortene', 'Å KAS-te KOR-te-ne', 'To throw the cards', 'To give up or admit defeat.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-15', 'norwegian', 'Å ha flere jern i ilden', 'Å ha FLE-re JERN i IL-den', 'To have several irons in the fire', 'To have multiple projects or options going at the same time.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-16', 'norwegian', 'Å sette ned foten', 'Å SET-te ned FO-ten', 'To put down one''s foot', 'To take a firm stand or put a stop to something.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-17', 'norwegian', 'Å være på trynet', 'Å VÄ-re på TRY-net', 'To be on the face', 'To fail or have bad luck.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-18', 'norwegian', 'Å blande kortene på nytt', 'Å BLAN-de KOR-te-ne på NYTT', 'To shuffle the cards again', 'To start over or try a different approach.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-19', 'norwegian', 'Å ha ryggen fri', 'Å ha RYG-gen FRI', 'To have one''s back free', 'To be without blame or to have nothing to worry about.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-20', 'norwegian', 'Å se rødt', 'Å se RÖTT', 'To see red', 'To become very angry.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-21', 'norwegian', 'Å dra lasset', 'Å DRA LAS-set', 'To pull the load', 'To do most of the work or carry the responsibility.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-22', 'norwegian', 'Å være i samme båt', 'Å VÄ-re i SAM-me BÅT', 'To be in the same boat', 'To be in the same situation or facing the same challenges.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-23', 'norwegian', 'Å kaste ut barnet med badevannet', 'Å KAS-te ut BAR-net med BA-de-van-net', 'To throw out the child with the bathwater', 'To discard something good while getting rid of something bad.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-24', 'norwegian', 'Å leve på lånt tid', 'Å LE-ve på LÅNT TID', 'To live on borrowed time', 'To be in a precarious situation or near the end of something.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-25', 'norwegian', 'Å tape ansikt', 'Å TA-pe AN-sikt', 'To lose face', 'To be embarrassed or lose one''s dignity.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-26', 'norwegian', 'Å bite i det sure eplet', 'Å BI-te i det SU-re EP-let', 'To bite the sour apple', 'To do something unpleasant that must be done.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-27', 'norwegian', 'Å gå på en smell', 'Å GÅ på en SMELL', 'To go on a blow', 'To take a risk or experience a setback.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-28', 'norwegian', 'Å ha tommelen midt i hånden', 'Å ha TOM-me-len MITT i HÅN-den', 'To have the thumb in the middle of the hand', 'To be clumsy or unskilled.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-29', 'norwegian', 'Å stikke hodet i sanden', 'Å STIK-ke HO-det i SAN-den', 'To stick one''s head in the sand', 'To ignore a problem and hope it goes away.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-30', 'norwegian', 'Å brenne inne med noe', 'Å BREN-ne IN-ne med NO-e', 'To burn inside with something', 'To have something you want to say but don''t.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-01', 'norwegian', 'Å ikke se skogen for bare trær', 'Å IK-ke se SKO-gen for BA-re TRÄR', 'To not see the forest for just trees', 'To get lost in details and miss the big picture.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-02', 'norwegian', 'Å ha is i magen', 'Å ha IS i MA-gen', 'To have ice in the stomach', 'To remain calm under pressure.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-03', 'norwegian', 'Å slå hull på myten', 'Å SLÅ HULL på MY-ten', 'To punch a hole in the myth', 'To disprove a common misconception.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-04', 'norwegian', 'Å være på bølgelengde', 'Å VÄ-re på BÖL-ge-leng-de', 'To be on the same wavelength', 'To understand each other perfectly.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-05', 'norwegian', 'Å kaste inn håndkleet', 'Å KAS-te inn HÅND-kle-et', 'To throw in the towel', 'To give up, just like in English.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-06', 'norwegian', 'Å snu hver krone', 'Å SNU HVER KRO-ne', 'To turn every crown', 'To be very careful with money.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-07', 'norwegian', 'Å gå på en smell', 'Å GÅ på en SMELL', 'To go on a blow', 'To experience a setback or failure.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-08', 'norwegian', 'Å lese mellom linjene', 'Å LE-se MEL-lom LIN-je-ne', 'To read between the lines', 'To understand the hidden meaning in what someone is saying.', NOW(), NOW());

-- Danish expressions (30 days)
INSERT INTO "Expression" (id, date, country, expression, pronunciation, meaning, translation, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), '2025-09-09', 'danish', 'At have en dag i høj hat', 'AT ha-ve en DAG i HÖJ HAT', 'To have a day in a tall hat', 'To have an exceptionally good or memorable day, to be in high spirits.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-10', 'danish', 'At stikke fingeren i jorden', 'AT STIK-ke FIN-ge-ren i JOR-den', 'To stick a finger in the ground', 'To test the waters or check the current situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-11', 'danish', 'At slå to fluer med ét smæk', 'AT SLÅ to FLU-er med ÉT SMÄK', 'To hit two flies with one swat', 'Similar to "kill two birds with one stone" in English.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-12', 'danish', 'At kaste håndklædet i ringen', 'AT KAS-te HÅND-klä-det i RIN-gen', 'To throw the towel in the ring', 'To give up, surrender, or admit defeat.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-13', 'danish', 'At have en gris på bordet', 'AT ha-ve en GRIS på BOR-det', 'To have a pig on the table', 'To have an uncomfortable or awkward situation that no one wants to address.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-14', 'danish', 'At falde på halen', 'AT FAL-de på HA-len', 'To fall on one''s tail', 'To be surprised or shocked by something unexpected.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-15', 'danish', 'At stå med skægget i postkassen', 'AT STÅ med SKÄG-get i POST-kas-sen', 'To stand with the beard in the mailbox', 'To be caught in an embarrassing or compromising situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-16', 'danish', 'At trække vejret lettere', 'AT TRÄK-ke VEJ-ret LET-te-re', 'To breathe more easily', 'To feel relieved or less stressed.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-17', 'danish', 'At have røven fuld af deller', 'AT ha-ve RÖ-ven FULD af DEL-ler', 'To have one''s bottom full of lumps', 'To be very lucky or have things go your way.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-18', 'danish', 'At rende ind i en blindgyde', 'AT REN-de ind i en BLIND-gy-de', 'To run into a blind alley', 'To reach a dead end or get stuck in a situation with no way forward.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-19', 'danish', 'At tage hatten af for', 'AT TA-ge HAT-ten af for', 'To take one''s hat off to', 'To show great respect or admiration.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-20', 'danish', 'At have en plet på avisen', 'AT ha-ve en PLET på A-vi-sen', 'To have a spot on the newspaper', 'To have a bad reputation or be slightly disgraced.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-21', 'danish', 'At ryge ud af et vindue', 'AT RY-ge ud af et VIN-due', 'To smoke out of a window', 'To lose an opportunity or be fired from a job.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-22', 'danish', 'At være på den grønne gren', 'AT VÄ-re på den GRÖN-ne GREN', 'To be on the green branch', 'To be successful or doing well financially.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-23', 'danish', 'At have en kæp i hjulet', 'AT ha-ve en KÄP i HJU-let', 'To have a stick in the wheel', 'To create an obstacle or intentionally make things difficult.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-24', 'danish', 'At stå med skjorterne uden på bukserne', 'AT STÅ med SKJOR-ter-ne U-den på BUK-ser-ne', 'To stand with shirts outside the pants', 'To be completely exposed or vulnerable.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-25', 'danish', 'At tage med et gran salt', 'AT TA-ge med et GRAN SALT', 'To take with a grain of salt', 'To be skeptical or not believe something completely.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-26', 'danish', 'At løbe landet rundt', 'AT LÖ-be LAN-det RUNDT', 'To run around the country', 'To travel extensively or be very busy.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-27', 'danish', 'At have høj musik på', 'AT ha-ve HÖJ MU-sik på', 'To have high music on', 'To be in a great mood or very excited.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-28', 'danish', 'At sove på begge ører', 'AT SO-ve på BEG-ge ÖR-er', 'To sleep on both ears', 'To sleep soundly and without worry.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-29', 'danish', 'At komme ud over stepperne', 'AT KOM-me ud O-ver STEP-per-ne', 'To come out over the steppes', 'To go beyond normal limits or do something extraordinary.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-30', 'danish', 'At have en finger med i spillet', 'AT ha-ve en FIN-ger med i SPIL-let', 'To have a finger in the game', 'To be involved or have influence in a situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-01', 'danish', 'At stikke hovedet i busken', 'AT STIK-ke HO-ve-det i BUS-ken', 'To stick one''s head in the bush', 'To avoid facing a problem or reality.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-02', 'danish', 'At være på bølgelængde', 'AT VÄ-re på BÖL-ge-läng-de', 'To be on the same wavelength', 'To understand each other perfectly.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-03', 'danish', 'At have is i maven', 'AT ha-ve IS i MA-ven', 'To have ice in the stomach', 'To remain calm under pressure.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-04', 'danish', 'At tage tingene i stiv arm', 'AT TA-ge TIN-ge-ne i STIV ARM', 'To take things in a stiff arm', 'To handle a situation with composure or not get upset.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-05', 'danish', 'At have en fed løn', 'AT ha-ve en FED LÖN', 'To have a fat salary', 'To earn a very good income.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-06', 'danish', 'At slå plat eller krone', 'AT SLÅ PLAT el-ler KRO-ne', 'To hit flat or crown', 'To flip a coin, similar to "heads or tails" in English.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-07', 'danish', 'At rende rundt som en ensom ulv', 'AT REN-de RUNDT som en EN-som ULV', 'To run around like a lonely wolf', 'To be alone or feel isolated.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-08', 'danish', 'At læse mellem linjerne', 'AT LÄ-se MEL-lem LIN-je-rne', 'To read between the lines', 'To understand the hidden meaning in what someone is saying.', NOW(), NOW());

-- Finnish expressions (30 days)
INSERT INTO "Expression" (id, date, country, expression, pronunciation, meaning, translation, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), '2025-09-09', 'finnish', 'Ottaa itseään niskasta kiinni', 'OT-taa IT-se-ään NIS-kas-ta KII-nni', 'To grab oneself by the neck', 'To pull oneself together, to take responsibility or make an effort.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-10', 'finnish', 'Ei oo kaikki muumit laaksossa', 'EI oo KAIK-ki MUU-mit LAAK-sos-sa', 'Not all the Moomins are in the valley', 'Something is not quite right, or someone is not entirely sane.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-11', 'finnish', 'Mennä puihin', 'MEN-nä PUI-hin', 'To go to the trees', 'To become angry or lose one''s temper.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-12', 'finnish', 'Vetää herneet nenään', 'VE-tää HER-neet NE-nään', 'To pull peas into the nose', 'To get offended or upset about something.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-13', 'finnish', 'Olla pilvillä', 'OL-la PIL-vil-lä', 'To be on the clouds', 'To be extremely happy or in a state of euphoria.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-14', 'finnish', 'Lyödä läpi', 'LYÖ-dä LÄ-pi', 'To hit through', 'To become successful or break through.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-15', 'finnish', 'Pistää hans päähän', 'PIS-tää HANS PÄÄ-hän', 'To stick in one''s head', 'To get an idea or sudden inspiration.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-16', 'finnish', 'Olla puulla päähän lyöty', 'OL-la PUU-l-la PÄÄ-hän LYÖ-ty', 'To be hit on the head with a piece of wood', 'To be stupid or not very bright.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-17', 'finnish', 'Mennä mönkään', 'MEN-nä MÖN-kään', 'To go crooked', 'To fail completely or go wrong.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-18', 'finnish', 'Vetää vertoja', 'VE-tää VER-to-ja', 'To draw parallels', 'To be equal to or as good as someone else.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-19', 'finnish', 'Olla neljännessä naurussa', 'OL-la NEL-jän-nes-sä NAU-rus-sa', 'To be in the fourth laugh', 'To be completely exhausted from laughing.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-20', 'finnish', 'Painaa päänsä pensaaseen', 'PAI-naa PÄÄ-nsä PEN-saa-seen', 'To press one''s head into the bush', 'To avoid facing a problem or reality.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-21', 'finnish', 'Olla kuin kotonaan', 'OL-la KU-in KO-to-naan', 'To be like at home', 'To feel completely comfortable in a situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-22', 'finnish', 'Lyödä hanskat tiskiin', 'LYÖ-dä HANS-kat TIS-kiin', 'To throw the gloves on the counter', 'To give up or surrender.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-23', 'finnish', 'Olla pitkällä', 'OL-la PIT-käl-lä', 'To be long', 'To be very advanced or far along in something.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-24', 'finnish', 'Vetää köyttä', 'VE-tää KÖY-tä', 'To pull the rope', 'To joke around or tease someone.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-25', 'finnish', 'Olla pää pyörällä', 'OL-la PÄÄ PYÖ-räl-lä', 'To have a head spinning', 'To be confused or disoriented.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-26', 'finnish', 'Mennä yli ymmärryksen', 'MEN-nä Y-li YM-mär-ryk-sen', 'To go beyond understanding', 'Something is incomprehensible or makes no sense.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-27', 'finnish', 'Ottaa lusikka kaukaloon', 'OT-taa LU-sik-ka KAU-ka-loon', 'To take the spoon to the trough', 'To join in, get involved, or start participating.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-28', 'finnish', 'Olla kuin vasten seinää', 'OL-la KU-in VAS-ten SEI-nää', 'To be like against a wall', 'To be in a difficult or hopeless situation.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-29', 'finnish', 'Luoda siltaa', 'LUO-da SIL-taa', 'To build a bridge', 'To create understanding or connection between people.', NOW(), NOW()),
(gen_random_uuid(), '2025-09-30', 'finnish', 'Olla kuin koira veräjässä', 'OL-la KU-in KOI-ra VE-rä-jäs-sä', 'To be like a dog at the gate', 'To be very excited or eager about something.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-01', 'finnish', 'Nostaa kynnystä', 'NOS-taa KYN-ny-stä', 'To raise the threshold', 'To make something more difficult or complicated.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-02', 'finnish', 'Mennä pitkäksi', 'MEN-nä PIT-käk-si', 'To go long', 'To become tedious or drag on too long.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-03', 'finnish', 'Olla kuin seinää vasten', 'OL-la KU-in SEI-nää VAS-ten', 'To be like against the wall', 'To feel stuck or have no way forward.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-04', 'finnish', 'Vetää herneet nenään', 'VE-tää HER-neet NE-nään', 'To pull peas into the nose', 'To get offended or upset easily.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-05', 'finnish', 'Olla kuin taivaan tuuli', 'OL-la KU-in TAI-vaan TUI-li', 'To be like the wind of heaven', 'To be unpredictable or constantly changing.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-06', 'finnish', 'Lyödä kättä päälle', 'LYÖ-dä KÄT-tä PÄÄ-lle', 'To strike hand upon', 'To make a deal or agreement.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-07', 'finnish', 'Olla kuin vailla järkeä', 'OL-la KU-in VAI-l-la JÄR-ke-ä', 'To be without reason', 'To be completely irrational or senseless.', NOW(), NOW()),
(gen_random_uuid(), '2025-10-08', 'finnish', 'Lukea rivien välistä', 'LU-kea RI-vien VÄ-lis-tä', 'To read between the lines', 'To understand the hidden meaning in what someone is saying.', NOW(), NOW());
